# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765072a0cbac66b4cb37cde0e46ef141817bd91dcc283b15de4fe7b93160d3f6f8e1434d8394bcc523798c992e354e49609c10b9d1eccb448158a2402291e38c

test:
  secret_key_base: 675698a01e61c86bec2375b07d3c6c99f8b37f5838d71b85e4edc1866bc40d091ad68382f6ec12157d501f115af0b5bb527e2446e54f97df8a0aaf35b254b46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
